version: "3"


volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  pg-local:
    image: postgres:14-alpine3.20
    env_file: "local.env"
    ports:
      - "54331:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data
    networks:
      - authNetworkLocal

  pg-prod:
    image: postgres:14-alpine3.20
    env_file:
      - prod.env
    ports:
      - "54331:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data

  migrator-local:
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg-local
    networks:
      - authNetworkLocal

  migrator-prod:
    image: cr.selcloud.ru/chigvero/migrator_image:latest
    restart: on-failure
    environment:
      DB_HOST: pg-prod

  auth-local:
    build:
      context: .
      dockerfile: local.Dockerfile
    restart: on-failure
    ports:
      - "50060:50060"
    env_file:
      - local.env
    networks:
      - authNetworkLocal

  auth-prod:
    depends_on:
      - pg-prod
    image: cr.selcloud.ru/chigvero/auth_image:latest
    ports:
      - "50060:50060"
    env_file:
      - local.env
    networks:
      - authNetworkLocal


networks:
  authNetworkLocal:
